apiVersion: v1
kind: Service
metadata:
  name: user-crud-service
spec:
  selector:
    app: user-crud 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110